const verbs = [
    { v1: 'work', v2: 'worked' },
    { v1: 'open', v2: 'opened' },
    { v1: 'love', v2: 'loved' },
    { v1: 'see', v2: 'saw' },
    { v1: 'go', v2: 'went', v3: 'goes' },
    { v1: 'know', v2: 'knew' },
    { v1: 'start', v2: 'started' },
    { v1: 'finish', v2: 'finished' },
    { v1: 'close', v2: 'closed' },
    { v1: 'live', v2: 'lived' },
    { v1: 'come', v2: 'came' },
    { v1: 'think', v2: 'thought' },
    { v1: 'help', v2: 'helped' },
    { v1: 'ask', v2: 'asked' },
    { v1: 'answer', v2: 'answered' },
    { v1: 'give', v2: 'gave' },
    { v1: 'take', v2: 'took' },
    { v1: 'hope', v2: 'hope' },
    { v1: 'speak', v2: 'spoke' },
    { v1: 'travel', v2: 'traveled' },
    { v1: 'write', v2: 'wrote' },
    { v1: 'play', v2: 'played' },
    { v1: 'apologize', v2: 'apologized' },
    { v1: 'read', v2: 'read' },
    { v1: 'sleep', v2: 'slept' },
    { v1: 'spend', v2: 'spent' },
    { v1: 'accompany', v2: 'accompanied', v3: 'accompanies' },
    { v1: 'promise', v2: 'promised' },
    { v1: 'have rest', v2: 'hed rest', v3: 'has rest' },
    { v1: 'get', v2: 'got' },
    { v1: 'hide', v2: 'hid' },
    { v1: 'buy', v2: 'bought', v3: 'buys' },
    { v1: 'sell', v2: 'sold' },
    { v1: 'pay', v2: 'paid', v3: 'pays' },
    { v1: 'make', v2: 'made' },
    { v1: 'choose', v2: 'chose' },
    { v1: 'try', v2: 'tried', v3: 'tries' },
    { v1: 'show', v2: 'showed' },
    { v1: 'turn', v2: 'turned' },
    { v1: 'wear', v2: 'wore' },
    { v1: 'fall', v2: 'fell' },
    { v1: 'miss', v2: 'missed', v3: 'misses' },
    { v1: 'release', v2: 'released' },
    { v1: 'cut', v2: 'cut' }
];
const pronoun = ["I", 'you', 'we', 'they', 'he', 'she'];
const askWord = ['Will', "Do", "Does", "Did"];

export {verbs, pronoun, askWord};